name: 05 - CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            
            - name: Prepare pnpm
              uses: pnpm/action-setup@v6
              with:
                version: 11
                run_install: false

            - name: Install dependecies
              run: |
                cd 10-ci-cd
                echo "::group::Install dependencies"
                pnpm install
                echo "::endgroup::"

            - name: Lint
              run: |
                cd 10-ci-cd
                echo "::group::Lint"
                pnpm lint
                echo "::endgroup::"

            - name: Test
              run: |
                cd 10-ci-cd
                echo "::group::Test"
                pnpm test
                echo "::endgroup::"

            - name: Build
              run: |
                cd 10-ci-cd
                echo "::group::Build"
                pnpm build
                echo "::endgroup::"